version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: ecoride_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: ecoride_user
      MYSQL_PASSWORD: ecoride_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./ecoride.sql:/docker-entrypoint-initdb.d/ecoride.sql
    networks:
      - ecoride

  app:
    build:
      context: ./docker/php      # RELATIF AU REPO GIT
      dockerfile: Dockerfile
    container_name: ecoride_app
    volumes:
      - ./:/var/www/html         # RELATIF AU REPO GIT
    depends_on:
      - db
      - mongodb
    networks:
      - ecoride
    command: >
      sh -c "
      if [ ! -f /var/www/html/vendor/autoload.php ]; then
        composer install --no-interaction --prefer-dist --optimize-autoloader;
      fi &&
      apache2-foreground
      "
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      - db
    networks:
      - ecoride

  mongodb:
    image: mongo:7.0
    container_name: ecoride_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb_user
      MONGO_INITDB_ROOT_PASSWORD: mongodb_pass
      MONGO_INITDB_DATABASE: ecoride
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecoride

volumes:
  mysql_data:
  mongodb_data:

networks:
  ecoride:
    external: true
    name: ecoride
